<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HOME-PC" name="AddTest" tests="1" failures="1" timestamp="7 Jun 2021 14:37:21 GMT" time="16.062" errors="0">
  <testcase name="TC_AdditionOfTwoNumbers" time="15.271" classname="TestCases.TC_Addition">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [111111] but found [11]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [111111] but found [11]
	at TestCases.TC_Addition.TC_AdditionOfTwoNumbers(TC_Addition.java:50)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TC_AdditionOfTwoNumbers -->
</testsuite> <!-- AddTest -->
